name: StaffWorksPlus
main: me.oppyusa.staffworksplus.Main
version: 0.0.2
commands:
  staffworks:
    description: Reloads the StaffWorksPlus plugin.
    permission: staffworks.reload
    usage:  /staffworks
  banhammer:
    description: Gives you the all mighty ban hammer!
    permission: staffworks.hammer
    usage:  /banhammer